### ISSUE TITLE
Consistente CSS 

### ISSUE THREAD

**Issue by Annevd** [lisavanmansom/tribeforlife-profilecard#19]
Bij sommige elementen zet je de properties en values op 1 line, en bij andere zet je ze onder elkaar. Probeer 1 van de twee te kiezen zodat je CSS consistent en goed leesbaar blijft.

https://github.com/lisavanmansom/tribeforlife-profilecard/blob/260a25b005182253549df02ba49aee2196486041/my-app/src/routes/%2Bpage.svelte#L268-L276

**Comment by lisavanmansom** [comment]
Bij hovers en @media is de code op 1 lijn. Bij andere code is het een opsomming onder elkaar. Dus het is wel consistent.
